CREATE TABLE IF NOT EXISTS pastime (
_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
name TEXT NOT NULL UNIQUE COLLATE NOCASE,
action_name TEXT DEFAULT NULL,
locale TEXT DEFAULT NULL,
active INTEGER NOT NULL DEFAULT 1,
custom INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS pastime_alias (
_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
pastime_id INTEGER NOT NULL REFERENCES pastime(_id),
name TEXT NOT NULL COLLATE NOCASE
);

CREATE TABLE IF NOT EXISTS selection_method (
_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
name TEXT NOT NULL UNIQUE COLLATE NOCASE
);

CREATE TABLE IF NOT EXISTS action (
_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
pastime_id INTEGER NOT NULL REFERENCES pastime(_id),
method_id INTEGER NOT NULL REFERENCES selection_method(_id),
performed INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
day INTEGER NOT NULL DEFAULT (CAST (strftime('%w', date('now'), 'localtime') AS INTEGER)) COLLATE NOCASE
);

CREATE TABLE IF NOT EXISTS statistic (
_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
name TEXT NOT NULL UNIQUE COLLATE NOCASE,
type TEXT NOT NULL COLLATE NOCASE
);

CREATE TABLE IF NOT EXISTS measurement (
_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
stat_id INTEGER NOT NULL REFERENCES statistic(_id),
action_id INTEGER NOT NULL REFERENCES action(_id),
value_integer INTEGER,
value_text TEXT COLLATE NOCASE
);

INSERT INTO selection_method
(name) VALUES
('ballast'),
('historical'),
('inactive'),
('random'),
('manual');

INSERT INTO statistic
(name, type) VALUES
('temperature', 'integer'),
('weather', 'text'),
('crowd', 'text');

